/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef FTSCAN_H
#define FTSCAN_H

/* function declarations */
void send_ftsClkTrap_trap(unsigned int clientreg,  void *clientarg);

void init_ftsCan(void);


#endif /* FTSCAN_H */
